-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgObRJOc0yMOccP7DX
1F0bUkAZ4Fu7OagKu1fdOWAoKrqgCgYIKoZIzj0DAQehRANCAATobpZ1VRmjCeef
jW/+DIsyyubYTNtJw7YZevo/EhSRHZkZGodcQj1+8CXj1vcDRwI2zEQxcxwiMOfF
9zBHsXFP
-----END PRIVATE KEY-----