server:
  port: 8080
  servlet:
    contextPath: "/api/pull-up/"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: pull-up
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.203.236.62:3306/pullup?serverTimezone=Asia/Seoul
    username: root
    password: 1077
    hikari:
      maximum-pool-size: 10
  # jpa
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000
        format_sql: true


  # social security
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f9165f4a6bb04401b296313ef583fb98
            client-secret: wt0MHHY0Dp9vTTUYX4w7M8yEDZUSebcg
#            redirect-uri: "https://pullup-api.shop/api/pull-up/oauth2/callback/kakao"
            redirect-uri: "http://localhost:8080/api/pull-up/oauth2/callback/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            clientName: kakao
          apple:
            client-id: com.pull-up.services
            #client-secret: AuthKey_SNHA348FS6.p8/7MKFVNQYN5/SNHA348FS6
            client-secret: AuthKey_SNHA348FS6.p8
            redirect-uri: "https://pullup-api.shop/api/pull-up/oauth2/callback/apple"
#            redirect-uri: "https://pullup-api.shop/login/oauth2/code/apple"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - name
              - email
            clientName: apple
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            tokenUri: https://appleid.apple.com/auth/token
#            jwk-set-uri: https://appleid.apple.com/auth/keys
#            user-name-attribute: sub

apple:
  url: https://appleid.apple.com
  path: static/apple/AuthKey_SNHA348FS6.p8
  cid: com.pull-up.services
  tid: 7MKFVNQYN5
  kid: SNHA348FS6

#logging
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: trace
    root: INFO
    org:
      springframework:
        web: INFO
        apache:
          tiles: DEBUG
        springframework:
          boot: DEBUG
