spring:
  profiles:
    group:
      prod:
      - prod
      - common
      dev:
      - dev
      - common
      local:
      - local
      - common
    default: local

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - file:./config/prod/pull-up-config.yml
---
spring:
  config:
    activate:
      on-profile: dev
    import: file:./config/dev/pull-up-config.yml
---
spring:
  config:
    activate:
      on-profile: local
    import: classpath:pull-up-config.yml
---
logging:
  level:
    org.hibernate.SQL: ${log.level.jpa}
    root: ${log.level.root}

server:
  port: ${basic-server.port}

spring:
  config:
    activate:
      on-profile: common

  application:
    name: pull-up

  datasource:
    driver-class-name: ${database.jdbc-driver}
    url: jdbc:${database.provider}://${database.ip}:${database.port}/${database.schema}?serverTimeZone=${database.timezone}
    username: ${database.username}
    password: ${database.password}

  # jpa
  jpa:
    hibernate:
      ddl-auto: ${database.jpa.ddl-auto}
    properties:
      hibernate:
        dialect: ${database.jpa.dialect}
        default_batch_fetch_size: ${database.jpa.batch-fetch}
        format_sql: ${database.jpa.format-sql}

  # social security
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${security.oauth2.kakao.client-id}
            client-secret: ${security.oauth2.kakao.client-secret}
            redirect-uri: ${security.oauth2.kakao.redirect-uri}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
            scope:
              - profile_nickname
          apple:
            client-id: ${security.oauth2.apple.client-id}
            redirect-uri: ${security.oauth2.apple.redirect-uri}
            authorization-grant-type: authorization_code
            client-authentication-method: form_post
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?response_mode=form_post&response_type=code%20id_token
            tokenUri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys

# custom auth config
auth:
  kakao:
    frontend-redirect-uri: ${security.oauth2.kakao.frontend-redirect-uri}
  apple:
    frontend-redirect-uri: ${security.oauth2.apple.frontend-redirect-uri}
    token:
      key-path: ${security.oauth2.apple.token.key-path}
      key-id: ${security.oauth2.apple.token.key-id}
      team-id: ${security.oauth2.apple.token.team-id}
      base-uri: ${security.oauth2.apple.token.base-uri}
      expire: ${security.oauth2.apple.token.expire}
  jwt:
    key: ${security.jwt.key}
    subject: ${security.jwt.subject}
    issuer: ${security.jwt.issuer}
    audience: ${security.jwt.audience}
    expire: ${security.jwt.expire}
  cookie:
    domain: ${security.cookie.domain}
    path: ${security.cookie.path}
    max-age: ${security.cookie.max-age}
  domain:
    frontend: ${basic-server.frontend-domain}
  with-credential: ${security.with-credential}

springdoc:
  use-fqn: true
